### ISSUE TITLE
Code block on the new theme

### ISSUE THREAD

**Issue by FBerthelot** [Zenika/zenika-formation-framework#233]
The new theme is great, but it's not clear when you have two code blocks in a row like this:

```html
<!-- fileA.html-->
<p>yolo</p>
```
```css
/* fileA.css */
.hugoWood {
  float: none;
}
```

Maybe you can add a border around the whole code block ?
